version: '3.3'
services:
  nginx:
    build: ../dockerfile/nginx-1.15.5
    ports:
      - "80:80" #nginx
    restart: always
    tty: true
    container_name: nginx
    volumes:
      - ../../www:/var/www/html
      - ../../logs/nginx:/var/log/nginx
      - ../config/nginx/conf.d:/etc/nginx/conf.d
      - ../config/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - lnmp-networks
  php7:
    build: ../dockerfile/php-7.2-fpm
    tty: true
    restart: always
    container_name: php7
    volumes:
      - ../../www:/var/www/html
      - ../../logs/php:/var/log/php
      - ../config/php/php.ini:/usr/local/etc/php/php.ini
      - ../config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - nginx
    networks:
      - lnmp-networks
  redis:
    build: ../dockerfile/redis-5.0.5
    container_name: redis
    tty: true
    restart: always
    volumes:
      - ../config/redis/redis.conf:/etc/redis/redis.conf
      - ../../redis:/var/lib/redis
      - ../../logs/redis:/var/log/redis
    networks:
      - lnmp-networks
  mysql:
    build: ../dockerfile/mysql-8.0.18
    container_name: mysql
    tty: true
    restart: always
    ports:
      - "3306:3306" #mysql
    volumes:
      - ../../mysql:/var/lib/mysql
      - ../config/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ../../logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - lnmp-networks
networks:
  lnmp-networks:
